apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  root-password: {{ .Values.secrets.mysql.rootPassword | b64enc }}
  db-password: {{ .Values.secrets.backend.dbPassword | b64enc }}
